### ISSUE TITLE
Fetch feed doesnt work

### ISSUE THREAD

**Issue by vozer** [aoout/obsidian-rss-copyist#3]
Plugin fails with following error when trying to fetch feed:

            (await this.getUrlContent(r)).items.slice(0, n).forEach(async u=>{
                Ye.htmlToMarkdown)(u.content);

![image](https://github.com/aoout/obsidian-rss-copyist/assets/2887707/a20a11f5-df62-4a38-bf58-c4953fc98d1a)

**Comment by aoout** [comment]
please tell me the rss link.

**Comment by Shyclops** [comment]
I also have some RSS feeds whic 
    
RSS Feed : https://www.tomscott.com/updates.xml

```    
Error: Uncaught (in promise) TypeError: undefined is not a string, or an element/document/fragment node.
    at k.turndown (turndown.js:2:9968)
    at yb (app.js:1:722835)
    at eval (plugin:rss-copyist:18:76640)
    at Array.forEach (<anonymous>)
    at Pi.syncFeed (plugin:rss-copyist:18:76595)    
   ```

RSS Feed : https://thesam.zone/tags/beryl/index.xml

```
plugin:rss-copyist:18 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at Pi.loadWebpageText (plugin:rss-copyist:18:77236)
    at eval (plugin:rss-copyist:18:76669)
    at Array.forEach (<anonymous>)
    at Pi.syncFeed (plugin:rss-copyist:18:76595)
```

RSS Feed : url: https://research.openanalysis.net/feed.xml

```
Uncaught (in promise) TypeError: undefined is not a string, or an element/document/fragment node.
    at k.turndown (turndown.js:2:9968)
    at yb (app.js:1:722835)
    at eval (plugin:rss-copyist:18:76640)
    at Array.forEach (<anonymous>)
    at Pi.syncFeed (plugin:rss-copyist:18:76595)
    ```

**Comment by jsoros** [comment]
My solution to `TypeError: Cannot read properties of null (reading 'path')`:  I had named my template file `template.md` and in reality this named it `template.md.md` because of hidden extensions. Once I renamed the template to remove the extra extension ".md", plugin started syncing feeds for me.
